name: CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "feature/*", "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Build and run tests
        run: |
          ./mvnw clean test
