name: Publish and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Build JAR
        run: |
          ./mvnw clean package -DskipTests

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u xlillium --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/xlillium/test-gh-deploy-backend:${{ github.sha }} .
          docker tag ghcr.io/xlillium/test-gh-deploy-backend:${{ github.sha }} ghcr.io/xlillium/test-gh-deploy-backend:latest

      - name: Push Docker Image
        run: |
          docker push ghcr.io/xlillium/test-gh-deploy-backend:${{ github.sha }}
          docker push ghcr.io/xlillium/test-gh-deploy-backend:latest

  deploy:
    needs: build-and-push-docker-image
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on VPS via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}

          script: |
            # docker login ghcr.io -u "${{ secrets.GHCR_USER }}" -p "${{ secrets.GHCR_TOKEN }}"

            env GIT_COMMIT_HASH=${{ github.sha }} docker stack deploy -c docker-stack.yml test-gh-deploy